version: '3.4'

services:
  quarkless:
    image: quarkless/quarkless.api
    container_name: api.quark
    build:
      context: .
      dockerfile: Quarkless/Dockerfile
    ports:
      - 51518:80
    volumes:
      - ./References/ffm:/ffm
    networks:
      localnet:
        aliases: 
          - quarkless.local.api
networks:
  localnet:
    external: true