version: '3.4'

services:
  quarkless.security:
    image: quarkless/quarkless.security
    container_name: quarkless.security.now
    build:
      context: .
      dockerfile: Quarkless.Security/Dockerfile
    ports:
      - 65115:80
    networks:
      local-network:
        aliases:
          - quarkless.net.security
  quarkless:
    image: quarkless/api
    container_name: quarkless.api.now
    build:
      context: .
      dockerfile: Quarkless/Dockerfile
    ports:
      - 51518:80
    networks:
      local-network:
         aliases:
          - quarkless.net.api
    depends_on:
      - quarkless.security
  quarkless.automator:
    image: quarkless/quarkless.services.automator
    container_name: quarkless.automator.now
    build:
      context: .
      dockerfile: Quarkless.Services/Dockerfile
    networks:
      - local-network
    depends_on:
      - quarkless.security
networks:
  local-network: