version: '3.4'

services:
  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    ports:
      - 4444:4444
    networks:
      local-network:
        aliases:
          - quarkless.net.selenium.hub
  quarkless.selenium.chrome:
    image: selenium/node-chrome:3.141.59-xenon
    container_name: quarkless.selenium.now
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      local-network:
        aliases:
          - quarkless.net.selenium.now
  quarkless.redis:
    image: redis:latest    
    container_name: quarkless.redis.now
    ports:
      - 6379:6379
    networks:
      local-network:
        aliases:
          - quarkless.net.redis-01
    volumes:
      - redisvol:/workspace/db
  quarkless.security:
    image: quarkless/quarkless.security
    container_name: quarkless.security.now
    build:
      context: .
      dockerfile: Quarkless.Security/Dockerfile
    ports:
      - 65115:80
    networks:
      local-network:
        aliases:
          - quarkless.net.security
    volumes:
      - sharedvol:/workspace/static
    depends_on:
      - quarkless.redis
      - quarkless.selenium.chrome
  quarkless.automator:
    image: quarkless/services/automator
    build:
      context: .
      dockerfile: Quarkless.Services/Dockerfile
    networks:
      - local-network
    depends_on:
      - quarkless.security
  quarkless:
    image: quarkless/api
    container_name: quarkless.api.now
    build:
      context: .
      dockerfile: Quarkless/Dockerfile
    ports:
      - 51518:80
    networks:
      - local-network
    volumes:
      - sharedvol:/workspace/static
    depends_on:
      - quarkless.security

networks:
  local-network:

volumes:
  sharedvol:
  redisvol: