version: '3.4'

services:
    quarkless:
        image: 762675489931.dkr.ecr.eu-west-2.amazonaws.com/quarkless:latest
        container_name: api.quark
        environment:
            - DOTNET_ENV_RELEASE=dev
        ports:
            - 51518:80
    chrome:
        image: selenium/standalone-chrome:latest
        container_name: chrome.quark
        ports:
            - 4444:4444