version: '3.4'

services:
  quarklessSecurity:
    image: quarkless/quarkless.security
    depends_on: 
      - quarklessredis
    build:
      context: .
      dockerfile: Quarkless.Security/Dockerfile
    ports:
      - 65115:80
    networks:
      local-network:
        aliases:
          - quarkless.security
  quarkless:
    image: quarkless/quarkless.api
    build:
      context: .
      dockerfile: Quarkless/Dockerfile
    ports:
      - 51518:80
    networks:
      local-network:
         aliases:
          - quarkless.api
    depends_on:
      - quarklessSecurity
  quarklessAutomator:
    image: quarkless/quarkless.services.automator
    build:
      context: .
      dockerfile: Quarkless.Services/Dockerfile
    networks:
      - local-network
    depends_on:
      - quarklessSecurity
  hub:
    image: selenium/hub:3.141.59-xenon
    ports:
      - 4444:4444
    networks:
      local-network:
        aliases:
          - quarkless.selenium.hub
  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    networks:
      local-network:
        aliases:
          - quarkless.selenium.chrome       
  quarklessredis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      local-network:
        aliases:
          - quarkless.net.redis-01 
networks:
  local-network:
    driver: overlay
    attachable: true
