version: '3.4'

services:
  quarklessSecurity:
    image: quarkless/quarkless.security
    build:
      context: .
      dockerfile: Quarkless.Security/Dockerfile
    ports:
      - 65115:80
    networks:
      local-network:
        aliases:
          - quarkless.security
  quarkless:
    image: quarkless/quarkless.api
    build:
      context: .
      dockerfile: Quarkless/Dockerfile
    ports:
      - 51518:80
    networks:
      local-network:
         aliases:
          - quarkless.api
    depends_on:
      - quarklessSecurity

networks:
  local-network: