version: '3.4'

services:
  quarklessAutomator:
    image: quarkless/quarkless.services.automator
    build:
      context: .
      dockerfile: Quarkless.Services/Dockerfile
    networks:
      - local-network
      - linux-services-net
    depends_on:
      - quarklessSecurity
  
networks:
  local-network:
  linux-services-net:
    external: true