version: '3.4'

services:
  redisll:
    image: redis:latest
    hostname: quarkless.db.redis
    ports:
      - 6379:6379
    volumes:
      - ../db/redis-data:/data
    networks:
      linux-services-net:
        aliases:
          - quarkless.net.redis-01
 
networks:
  linux-services-net:
    external: true
