version: '3.4'

services:
  hub:
    image: selenium/hub:3.141.59-xenon
    ports:
      - 4444:4444
    networks:
      local-network:
        aliases:
          - quarkless.selenium.hub
  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    networks:
      local-network:
        aliases:
          - quarkless.selenium.chrome
  quarklessredis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      local-network:
        aliases:
          - quarkless.net.redis-01
 
networks:
  local-network: