version: '3.4'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: quarkless.selenium.chrome
    ports:
      - 4444:4444
    networks:
      linux-services-net:
        aliases:
          - selenium.hub.chrome
  redis:
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    image: redis:latest
    hostname: quarkless.db.redis
    ports:
      - 6379:6379
    networks:
      linux-services-net:
        aliases:
          - quarkless.net.redis-01
    volumes:
      - ../db/redis-data:/data
 
networks:
  linux-services-net:
    external: true