version: '3.4'

services:
  hub:
    image: selenium/hub:3
    hostname: quarkless.selenium.hub
    ports:
      - 4444:4444
    networks:
      linux-services-net:
        aliases:
          - selenium.hub
  chrome:
    image: selenium/node-chrome:3
    hostname: quarkless.selenium.chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    volumes:
      - ../dev/shm:/dev/shm
    networks:
      linux-services-net:
        aliases:
          - quarkless.selenium.chrome
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
  redisll:
    image: redis:latest
    hostname: quarkless.db.redis
    ports:
      - 6379:6379
    volumes:
      - ../db/redis-data:/data
    networks:
      linux-services-net:
        aliases:
          - quarkless.net.redis-01
 
networks:
  linux-services-net:
    external: true