version: "3.4"

services:
    google_search:
        image: quarkless/quarkless.python/google
        build:
            context: .
            dockerfile: GoogleSearch/Dockerfile
        container_name: googlesearch.quark
        ports:
            - 5000:5000
        networks:
            localnet:
                aliases: 
                - quarkless.local.googlesearch
    language_process:
        image: quarkless/quarkless.python/language_process
        build:
            context: .
            dockerfile: LanguageProcessing/Api/Dockerfile
        container_name: language.quark
        ports:
            - 5005:5005
        networks:
            localnet:
                aliases: 
                - quarkless.local.langprocess
networks:
    localnet:
        external: true