module.exports.Calling = {
  "base_path": process.env.VUE_APP_API,
  "account_login": process.env.VUE_APP_ACCOUNT_LOGIN,
  "account_refresh" : process.env.VUE_APP_ACCOUNT_REFRESH,
  "account_confirmation": process.env.VUE_APP_ACCOUNT_CONFIRMATION,
  "account_changepp": process.env.VUE_APP_ACCOUNT_CHANGEPP,
  "account_changebio": process.env.VUE_APP_ACCOUNT_CHANGEBIO,
  "account_get_instagrams_account": process.env.VUE_APP_ACCOUNT_GET_INSTAGRAMS_ACCOUNT,
  "account_get_user_instagram_account": process.env.VUE_APP_ACCOUNT_GET_USER_INSTAGRAM_ACCOUNT_STATE,
  "account_update_agent_state": process.env.VUE_APP_ACCOUNT_UPDATE_AGENT_STATE,
  "account_add_instagram": process.env.VUE_APP_ACCOUNT_ADD_INSTAGRAM,
  "account_instagram_challenge": process.env.VUE_APP_ACCOUNT_INSTAGRAM_CHALLENGE,
  "account_instagram_refresh": process.env.VUE_APP_ACCOUNT_INSTAGRAM_REFRESH,
  "account_get_profiles": process.env.VUE_APP_ACCOUNT_GET_PROFILES,
  "account_update_profile": process.env.VUE_APP_ACCOUNT_UPDATE_PROFILE,
  "account_add_profile_topics": process.env.VUE_APP_PROFILE_ADD_TOPICS,
  "account_upload": process.env.VUE_APP_ACCOUNT_UPLOAD,
  "account_session": process.env.VUE_APP_ACCOUNT_SESSION,

  "query_config": process.env.VUE_APP_QUERY_CONFIG,
  "query_related_by_parent": process.env.VUE_APP_QUERY_RELATED_TOPIC,
  "query_place_search": process.env.VUE_APP_QUERY_PLACE_SEARCH,
  "query_place_autocomplete": process.env.VUE_APP_QUERY_PLACE_AUTOCOMPLETE,
  "query_similar_image_search": process.env.VUE_APP_QUERY_SIMILAR_IMAGE_SEARCH,
  "query_related_topics": process.env.VUE_APP_QUERY_RELATED_TOPICS,
  "query_buildtags": process.env.VUE_APP_QUERY_BUILDTAGS,
  "query_searchTopic": process.env.VUE_APP_QUERY_SEARCHTOPIC,
  "query_searchLocation": process.env.VUE_APP_QUERY_SEARCHLOCATION,
  "query_userMedia": process.env.VUE_APP_QUERY_USERMEDIA,
  "query_userInbox": process.env.VUE_APP_QUERY_USERINBOX,
  "query_userFeed": process.env.VUE_APP_QUERY_USERFEED,
  "query_recentComments": process.env.VUE_APP_QUERY_RECENTCOMMENTS,
  "query_userFollowerList" : process.env.VUE_APP_QUERY_USERFOLLOWERLIST,
  "query_userFollowingList" : process.env.VUE_APP_QUERY_USERFOLLOWINGLIST,
  "query_userTargetLocation" : process.env.VUE_APP_QUERY_USERTARGETLOCATION,
  "query_userTargetList" : process.env.VUE_APP_QUERY_USERTARGETLIST,
  "query_userFollowingSuggestions" : process.env.VUE_APP_QUERY_USERFOLLOWINGSUGGESTIONS,
  "query_mediaByLocation" : process.env.VUE_APP_QUERY_MEDIABYLOCATION,

  "messaging_thread": process.env.VUE_APP_MESSAGING_THREAD,
  "messaging_post_text": process.env.VUE_APP_MESSAGING_POST_TEXT,
  "messaging_delete_comment": process.env.VUE_APP_MESSAGING_DELETE_COMMENT,
  "messaging_like_comment": process.env.VUE_APP_MESSAGING_LIKE_COMMENT,
  "messaging_unlike_comment": process.env.VUE_APP_MESSAGING_UNLIKE_COMMENT,
  "messaging_reply_comment": process.env.VUE_APP_MESSAGING_REPLY_COMMENT,
  "messaging_create_comment": process.env.VUE_APP_MESSAGING_CREATE_COMMENT,

  "timeline_get_user_timeline": process.env.VUE_APP_TIMELINE_GET_USER_TIMELINE,
  "timeline_delete_event": process.env.VUE_APP_TIMELINE_DELETE_EVENT,
  "timeline_enqueue_event": process.env.VUE_APP_TIMELINE_ENQUEUE_EVENT,
  "timeline_update_event": process.env.VUE_APP_TIMELINE_UPDATE_EVENT,
  "timeline_create_post": process.env.VUE_APP_TIMELINE_CREATE_POST,
  "timeline_create_message" : process.env.VUE_APP_TIMELINE_CREATE_MESSAGE,
  "timeline_get_event_logs": process.env.VUE_APP_TIMELINE_GET_EVENT_LOGS,
  "timeline_get_event_logs_for_user": process.env.VUE_APP_TIMELINE_GET_EVENT_LOGS_FOR_USER,

  "library_get_captions": process.env.VUE_APP_LIBRARY_GET_CAPTIONS,
  "library_get_medias": process.env.VUE_APP_LIBRARY_GET_MEDIAS,
  "library_get_hashtags": process.env.VUE_APP_LIBRARY_GET_HASHTAGS,
  "library_get_messages": process.env.VUE_APP_LIBRARY_GET_MESSAGES,
  "library_get_captions_for_user": process.env.VUE_APP_LIBRARY_GET_CAPTIONS_FOR_USER,
  "library_get_medias_for_user": process.env.VUE_APP_LIBRARY_GET_MEDIAS_FOR_USER,
  "library_get_hashtags_for_user": process.env.VUE_APP_LIBRARY_GET_HASHTAGS_FOR_USER,
  "library_get_messages_for_user": process.env.VUE_APP_LIBRARY_GET_MESSAGES_FOR_USER,
  "library_set_captions": process.env.VUE_APP_LIBRARY_SET_CAPTIONS,
  "library_set_medias": process.env.VUE_APP_LIBRARY_SET_MEDIAS,
  "library_set_hashtags": process.env.VUE_APP_LIBRARY_SET_HASHTAGS,
  "library_set_messages": process.env.VUE_APP_LIBRARY_SET_MESSAGES,
  "library_update_captions": process.env.VUE_APP_LIBRARY_UPDATE_CAPTIONS,
  "library_update_hashtags": process.env.VUE_APP_LIBRARY_UPDATE_HASHTAGS,
  "library_update_messages": process.env.VUE_APP_LIBRARY_UPDATE_MESSAGES,
  "library_delete_captions": process.env.VUE_APP_LIBRARY_DELETE_CAPTIONS,
  "library_delete_medias": process.env.VUE_APP_LIBRARY_DELETE_MEDIAS,
  "library_delete_hashtags": process.env.VUE_APP_LIBRARY_DELETE_HASHTAGS,
  "library_delete_messages": process.env.VUE_APP_LIBRARY_DELETE_MESSAGES,
}