module.exports.Calling = {
  "query_config": 'query/config',
  "query_place_search":'query/search/places/',
  "query_place_autocomplete":'query/search/places/auto/',
  "query_similar_image_search":'query/search/similar/',
  "query_related_topics":'query/releated/',
  "query_buildtags":'query/build/tags/',
  "query_searchTopic":'query/searchUserTopic/',
  "query_searchLocation":'query/searchUserLocation/',
  "query_userMedia":'query/userMedias/',
  "query_userInbox":'query/userInbox/',
  "query_userFeed": 'query/userFeed/',
  "query_recentComments":'query/recentComments/',
  "query_userFollowerList" : 'query/userFollowerList/',
  "query_userFollowingList" : 'query/userFollowingList/',
  "query_userTargetLocation" : 'query/userLocation/',
  "query_userTargetList" : 'query/userTargetList/',
  "query_userFollowingSuggestions" : 'query/userSuggestionFollowing/',
  "query_mediaByLocation" : 'query/mediasLocation/',
  "messaging_thread":'messaging/thread/',
  "messaging_post_text":'messaging/',
  "messaging_delete_comment":'comments/delete/',
  "messaging_like_comment": 'comments/like/',
  "messaging_unlike_comment": 'comments/unlike/',
  "messaging_reply_comment": 'comments/reply/',
  "messaging_create_comment": 'comments/create/'
}